### ISSUE TITLE
Fuzzer finds trivial failing input

### ISSUE THREAD

**Issue by barafael** [stalwartlabs/mail-parser#21]
Here's what happened:

```cargo +nightly fuzz run mail_parser```

as per the README instructions.

```
> cargo +nightly fuzz run mail_parser                                                    Fr 03 Jun 2022 23:07:55 CEST
    Finished release [optimized] target(s) in 0.04s
    Finished release [optimized] target(s) in 0.01s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser -artifact_prefix=/home/rafaelbachmann/mail-parser/fuzz/artifacts/mail_parser/ /home/rafaelbachmann/mail-parser/fuzz/corpus/mail_parser`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2065534056
INFO: Loaded 1 modules   (61288 inline 8-bit counters): 61288 [0x5589690a76b0, 0x5589690b6618), 
INFO: Loaded 1 PC tables (61288 PCs): 61288 [0x5589690b6618,0x5589691a5c98), 
INFO:        0 files found in /home/rafaelbachmann/mail-parser/fuzz/corpus/mail_parser
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/rafaelbachmann/mail-parser/src/parsers/mime.rs:67:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==10675== ERROR: libFuzzer: deadly signal
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
    #0 0x558968b608e1 in __sanitizer_print_stack_trace /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x558968e66cf0 in fuzzer::PrintStackTrace() (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x559cf0) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #2 0x558968e3b1ba in fuzzer::Fuzzer::CrashCallback() (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x52e1ba) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #3 0x7f6746db641f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #4 0x7f6746a9c00a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7f6746a9c00a in raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7f6746a7b858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
    #7 0x558968ecd3f6 in std::sys::unix::abort_internal::hd784c2ef4eaef268 /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys/unix/mod.rs:259:14
    #8 0x558968ad3e76 in std::process::abort::h12b81f6813977ba4 /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/process.rs:2059:5
    #9 0x558968e38655 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h8a37e105738cfca6 (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x52b655) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #10 0x558968ec2ea5 in std::panicking::rust_panic_with_hook::h6a32c5574ceba44d /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:702:17
    #11 0x558968ec2c68 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h33a7eb85cc49019a /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:586:13
    #12 0x558968ebfe73 in std::sys_common::backtrace::__rust_end_short_backtrace::hbc4249165d4ceafc /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:138:18
    #13 0x558968ec29d8 in rust_begin_unwind /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:584:5
    #14 0x558968ad50b2 in core::panicking::panic_fmt::hea2f72507c137b32 /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/core/src/panicking.rs:142:14
    #15 0x558968ad4f7c in core::panicking::panic::h942261c821499600 /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/core/src/panicking.rs:48:5
    #16 0x558968ce321e in mail_parser::parsers::mime::get_bytes_to_boundary::hc74c4ee90d8a356b (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x3d621e) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #17 0x558968baba84 in rust_fuzzer_test_input (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x29ea84) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #18 0x558968e387a8 in __rust_try (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x52b7a8) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #19 0x558968e37bd8 in LLVMFuzzerTestOneInput (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x52abd8) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #20 0x558968e3b6fc in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x52e6fc) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #21 0x558968e452b3 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x5382b3) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #22 0x558968e46c1b in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x539c1b) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #23 0x558968e483cc in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x53b3cc) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #24 0x558968e65709 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x558709) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #25 0x558968ad5466 in main (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x1c8466) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)
    #26 0x7f6746a7d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #27 0x558968ad55cd in _start (/home/rafaelbachmann/mail-parser/fuzz/target/x86_64-unknown-linux-gnu/release/mail_parser+0x1c85cd) (BuildId: 57d82c60d90e286c0c8bad5e2bcebec0bf087d15)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xa,
\x0a
artifact_prefix='/home/rafaelbachmann/mail-parser/fuzz/artifacts/mail_parser/'; Test unit written to /home/rafaelbachmann/mail-parser/fuzz/artifacts/mail_parser/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Base64: Cg==

────────────────────────────────────────────────────────────────────────────────

Failing input:

        fuzz/artifacts/mail_parser/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc

Output of `std::fmt::Debug`:

        [10]

Reproduce with:

        cargo fuzz run mail_parser fuzz/artifacts/mail_parser/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc

Minimize test case with:

        cargo fuzz tmin mail_parser fuzz/artifacts/mail_parser/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 77
```

**Comment by mdecimus** [comment]
Thanks, I'll have a look a it on Monday and post a fix.
