### ISSUE TITLE
MHTML Snapshot of Google Fails To Parse CSS Attachments

### ISSUE THREAD

**Issue by quesurifn** [stalwartlabs/mail-parser#28]
Hello, I have an issue with MHTML parsing from snapshots taken with the Chrome API.

Given the following file found here:

https://gist.github.com/quesurifn/f6d5c7068a916b9f46927a01fd87ed36

When iterating through attachments and parsing each one, the first attachment to be passed through to `for_each` is the css.  E.g. 

```
"sM5MNb" aria-live=3D"polite" class=3D"SaJ9Qe"></div></div></body></html>
------MultipartBoundary--iWpBqfSwVqslpqB6usfCGkX1ZOR2Vavef3mICKj83Y----
Content-Type: text/css
Content-Transfer-Encoding: quoted-printable
Content-Location: cid:css-78b4b57b-c109-4f31-8d67-e691c0da5b1e@mhtml.blink

@charset "utf-8";

html, body, h1, input, select { font-family: arial, sans-serif; }

body, h1 { font-size: 14px; }

h1 { font-weight: normal; margin: 0px; padding: 0px; }

h3 { font-weight: normal; margin: 0px; padding: 0px; font-size: 20px; line-=
height: 1.3; }

body { margin: 0px; background: rgb(255, 255, 255); color: rgb(32, 33, 36);=
 }
 ```
 
 Given the following code:
 
 ```
    let path = fs::canonicalize(Path::new("./src/file.txt")).unwrap();
    let foo = fs::read_to_string(path).unwrap_or_default();
    let message = Message::parse(foo.as_bytes()).unwrap();
    let mut body = message.get_html_body(0).unwrap_or_default();
    message.get_html_bodies().for_each(|f| {
        let id = f.get_content_id().unwrap();
        println!("{}", id)
    });
    message.parts.iter().for_each(|f| {
       >>> let m  = f.parse_message().unwrap(); <--- Panics here
        let id = m.get_content_id().unwrap();
        println!("{}", id)
    });
```
With the following stack trace:

```
thread 'main' panicked at 'Expected message part.', /Users/kylefahey/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.4.8/src/lib.rs:436:18
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:616:12
   1: mail_parser::MessagePart::parse_message
             at /Users/kylefahey/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.4.8/src/lib.rs:436:18
   2: sandbox::main::{{closure}}
             at ./src/main.rs:17:18
   3: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/slice/iter/macros.rs:211:21
   4: sandbox::main
             at ./src/main.rs:16:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
```

**Comment by mdecimus** [comment]
Hi,

The code is panicking because you are calling `parse_message()` on a message part that it is not a nested rfc822 message. I took a look at the message you attached and there are no nested parts inside it. I also noticed that you are using an old version of mail-parser (0.4.8), if you upgrade to **0.5** or **0.6** (released today) this is the code that will print all Content-IDs of a message and returns None instead of panicking when called on a non-rfc822 part:

```
        let path = fs::canonicalize(std::path::Path::new("./file.txt")).unwrap();
        let foo = fs::read_to_string(path).unwrap_or_default();
        let message = Message::parse(foo.as_bytes()).unwrap();

        message.parts.iter().for_each(|f| {
            let id = f.get_content_id().unwrap_or("<none>");
            if let Some(message) = f.get_message() {
                println!(
                    "Nested message Cid: {}",
                    message.get_content_id().unwrap_or("<none>")
                )
            } else if f.is_text_html() {
                println!("Html Cid: {}", id)
            } else if f.is_text() {
                println!("Text Cid: {}", id)
            } else {
                println!("Other Cid: {}", id)
            }
        });
```

**Comment by quesurifn** [comment]
Maruo, 

I really appreciate you getting back to me. Usually, with Open Source software you're lucky if anyone ever gets back to you.
My understanding of MHTML is not the greatest so thanks pointing out both about the lack of nested parts and the fact that the message was not non-rfc822 compliant. I do find it curious that the attachments count was listed as 42 (or something around there) and the older version wasn't parsing said attachments. 

There was no specific reason I was using an old version. I think I was linked via google and didn't bother looking for the most recent version. I will use the snippet and will update to 0.6 with what you posted above.

Thanks.

**Comment by mdecimus** [comment]
Hi Kyle,

You're welcome! I hope that with the code snippet above you could parse the MHTML properly.
